[package]
name = "ruT0-data-kit-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yml = "0.0.12"
regex = "1"
csv = "1"
calamine = "0.24"

# T13-1 加密工具依赖
aes = "0.8"
cbc = { version = "0.1", features = ["block-padding"] }
cipher = "0.4"
base64 = "0.22"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
